from pathlib import Path

from chat.models import ChatResponse
from chat.service import ChatService
from config.settings import load_settings
from core.logging_setup import configure_logging
from core.model_router import ModelRouter
from files.authorization import FileAuthorizer
from files.service import FileService
from memory.manager import MemoryManager
from memory.store import MemoryStore
from security.policy import PermissionLevel, evaluate_permission


PROJECT_ROOT = Path(__file__).resolve().parent
MEMORY_PATH = PROJECT_ROOT / "data" / "memory.json"
FILE_KNOWLEDGE_ROOT = PROJECT_ROOT / "data" / "knowledge"


def create_memory_manager() -> MemoryManager:
    store = MemoryStore(str(MEMORY_PATH))
    return MemoryManager(store)


def create_file_service() -> FileService:
    FILE_KNOWLEDGE_ROOT.mkdir(parents=True, exist_ok=True)

    authorizer = FileAuthorizer([
        str(FILE_KNOWLEDGE_ROOT)
    ])

    return FileService(
        authorizer=authorizer
    )


def create_chat_service() -> ChatService:
    router = ModelRouter()
    memory = create_memory_manager()
    files = create_file_service()

    return ChatService(
        router=router,
        memory=memory,
        files=files,
    )


def main(user_text: str | None = None) -> ChatResponse | None:
    settings = load_settings()
    logger = configure_logging(settings.log_level)

    decision = evaluate_permission(
        PermissionLevel.READ_ONLY,
        confirmed=False,
    )

    logger.info("ANNA AI foundation started.")
    logger.info("Environment: %s", settings.environment)
    logger.info("Privacy mode: %s", settings.privacy_mode)
    logger.info(
        "Read-only policy check: allowed=%s",
        decision.allowed,
    )

    if user_text is None:
        print("ANNA AI foundation is running.")
        return None

    service = create_chat_service()

    response = service.respond(user_text)

    logger.info(
        "Chat response generated by provider=%s model=%s",
        response.provider,
        response.model,
    )

    print(response.message.content)

    return response


if __name__ == "__main__":
    main()
